apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: s3-dataset
spec:
  mounts:
    - mountPoint: s3://${BUCKET_NAME}/fluid/
      name: s3-mount      
      options:
        alluxio.underfs.s3.region: us-west-2
        alluxio.underfs.s3.endpoint: s3.us-west-2.amazonaws.com
      encryptOptions:
      - name: aws.accessKeyId
        valueFrom:
          secretKeyRef:
            name: data-set-secret
            key: aws.accessKeyId
      - name: aws.secretKey
        valueFrom:
          secretKeyRef:
            name: data-set-secret
            key: aws.secretKey
  accessModes:
    - ReadWriteMany
  placement: "Shared"