apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-dataset
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchExpressions:
    - key: name
      operator: In
      values: ["s3-dataset"]    
#  selector:
#    matchLabels:
#      dataset.fluid.io/name: s3-dataset
#      dataset.fluid.io/namespace: fluid-system
